feat(google): add `glyphs` option for font optimization
unjs/unifont pull request #80
Opened 2024-12-18 09:29 UTC by sushichan044

- resolves #61 

This PR adds a `glyphs` option for specifying characters and icons to fetch.

Users can resolve minimized fonts by using the `glyphs` option in Google Fonts and Google Icons.

2024-12-18 09:35 UTC, sushichan044 commented
I'm doing additional work to apply optimization by the glyphs option even when `Material Icons` is specified in the Google Icons provider.

2024-12-18 09:36 UTC, sushichan044 commented on test/providers/google.test.ts
> +    expect(fonts).toMatchInlineSnapshot(`
Since the URL parameters were the only way to verify that the correctly optimized fonts were resolved, I did a snapshot test.

2024-12-18 14:57 UTC, sushichan044 commented
Using the `glyphs` option while fetching `Material Icons` with Google Icons Provider is temporarily unsupported because of the different endpoints.

2025-04-09 10:42 UTC, qwerzl requested changes
The rest looks great to me. Thank you!

2025-04-09 10:42 UTC, qwerzl commented on src/types.ts
> +  /**
As other providers don't support setting glyphs yet (google really is ahead of the game), how about moving these to provider-specific options? I’d suggest taking a similar approach to how we added support for google's variable axes (#35). 

i.e.:

```typescript
interface ProviderOption {
  experimental: {
    glyphs?: {
      // font-name: ['Hello', 'World']
      [key: string]: string[]
    }
  }
}
```

The rest looks great to me. Thank you!

2025-04-09 12:56 UTC, sushichan044 commented on src/types.ts
> +  /**
Thank you! I'll make the change as I think it's better for current situation.

2025-04-09 13:05 UTC, sushichan044 commented
@danielroe @qwerzl 
This repository was used in a previous university experiment and is now read-only, so I need to contact the administrator.
It may take some time, but should I re-create a new PR from my fork?

2025-04-09 13:12 UTC, sushichan044 commented
I was able to unarchive fork. Never mind 🙏

2025-04-09 13:33 UTC, sushichan044 commented on src/providers/googleicons.ts
> +    }
I did not use `iconNames` because it is easier to understand if the names are aligned with those of other providers.

2025-04-09 14:04 UTC, qwerzl commented
LGTM. One last thing, @sushichan044 would you update the test snapshot? 🙏

2025-04-09 14:10 UTC, sushichan044 commented
I'll try to run the test in the US via VPN.

2025-04-09 14:26 UTC, sushichan044 commented
Looks like the reason the test fails is not a geographic factor.

2025-04-09 14:30 UTC, sushichan044 commented
I understood. I need to rebase to the latest master branch.

2025-04-09 14:55 UTC, sushichan044 commented
@qwerzl 
The snapshot after rebasing was the same as the one presented by GitHub Actions. Perhaps it's fixed.

2025-04-09 15:05 UTC, danielroe commented
it might be beneficial to clean up the hashes in the snapshot, while preserving the query parameters?

2025-04-09 15:13 UTC, sushichan044 commented
Sure, it might be better to take snapshots of only the properties we need.

2025-04-09 23:21 UTC, qwerzl commented
Hmm - we might need a utility to change the `src.urls` generated by google to something generic like `font-url.woff`. I'll look into that later.

2025-04-10 00:29 UTC, qwerzl commented
Looks like I don't have the permission to push to the repo. You could use `sanitizeFontSource` from `utils.ts` to sanitize the snapshot first.

2025-04-10 04:11 UTC, sushichan044 commented
Since the only way to know that this function is working correctly is through the query parameters,
like `https://fonts.gstatic.com/l/font?kit=pxiEyp8kv8JHgFVrFJXUdVNFIvDDHy0hxgHa&skey=87759fb096548f6d&v=v22` .
saniziting makes it impossible to test it.
```ts
    const sanitized = sanitizeFontSource(fonts)
    expect(sanitized).toMatchInlineSnapshot(`
      [
        {
          "meta": {
            "priority": 0,
          },
          "src": [
            {
              "format": "woff2",
              "url": "https://fonts.gstatic.com/font",
            },
          ],
          "style": "normal",
          "weight": 400,
        },
        {
          "meta": {
            "priority": 1,
          },
          "src": [
            {
              "format": "woff",
              "url": "https://fonts.gstatic.com/font",
            },
          ],
          "style": "normal",
          "weight": 400,
        },
      ]
    `)
```

2025-04-10 04:15 UTC, sushichan044 commented
I think it would be nice to create a utility that would be concerned with font sources. I'll try it later.

2025-04-13 08:30 UTC, sushichan044 commented
@qwerzl 
I created a utility specifically for optimized urls.
The tests might be a little easier to see.

2025-04-13 08:32 UTC, sushichan044 commented on test/utils/index.ts
> +  }
In fact, only the v parameter is changed in [this CI](https://github.com/unjs/unifont/actions/runs/14361020445/job/40287557200).

Also, when I ran it earlier in my environment, v was further increased to 237.

2025-04-17 15:49 UTC, qwerzl approved these changes
LGTM. Thank you!

2025-04-17 16:12 UTC, merged